### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by hallo096** [john-kloss/rudi#1]
Hey,
I want to use the tool for our running-dinner therefore i have to adjust some things and i wanted to ask if you can tell me where i can find the part where the teams are connected to a meal.
It would be a huge help if you can answer this question.

Ich würde gerne das Tool für unser Running-Dinner benutzen aber da wir die Einteilung der Gänge selber machen wollen, müsste ich etwas am Code ändern. Nun wollte ich fragen ob Sie mir evt. sagen könnten wo im Code die Zuordnung stattfindet. Bzw. wäre es möglich eine Funktion dafür zu implementieren das diese manuell stattfindet?

**Comment by hallo096** [comment]
+Transforming to email don´t work properly phonenumber is displayed on other line etc.

**Comment by john-kloss** [comment]
Hi,
klar ich denke, dass das möglich wäre. Kannst du mir genau sagen, worum es geht? Du möchtest bestimmten Teams bestimmte Gänge zuordnen?

Kannst du mir einen Screenshot von dem Problem mit den Telefonnummern schicken?
